package com.kapilguru.trainer.ui.webiner.model

import com.google.gson.annotations.SerializedName
import java.io.Serializable

open class ActiveWebinarData(
    @SerializedName("about") var about: String? = "",
    @SerializedName("code") var code: String ? ="",
    @SerializedName("course_id") var courseId: Int = 0,
    @SerializedName("created_by") var createdBy: Int= 0,
    @SerializedName("created_date") var createdDate: String? = "",
    @SerializedName("duration_days") var durationDays: Int = 0,
    @SerializedName("duration_hrs") var durationHrs: Int = 0,
    @SerializedName("end_date") var endDate: String? = null, //2021-12-23T14:00:00.000Z
    @SerializedName("end_time") var endTime: String? = "",
    @SerializedName("id") var id: Int = 0,
    @SerializedName("image") var image: String? = null,
    @SerializedName("is_active") var isActive: Int = 0,
    @SerializedName("is_conducted") var isConducted: Int = 0,
    @SerializedName("is_paid") var isPaid: Int = 0,
    @SerializedName("is_requested") var isRequested: Int = 0,
    @SerializedName("languages") var languages: String? = "",
    @SerializedName("modified_by") var modifiedBy: String? = "",
    @SerializedName("modified_date") var modifiedDate: String? = "",
    @SerializedName("no_of_attendees") var noOfAttendees: Int = 0,
    @SerializedName("registered_no_of_attendees") var registeredAttendees: Int = 0,
    @SerializedName("paid_date") var paidDate: String? = "",
    @SerializedName("price") var price: Int = 0,
    @SerializedName("request_money_id") var requestMoneyId: Int = 0,
    @SerializedName("requested_date") var requestedDate: String? = "",
    @SerializedName("speaker_name") var speakerName: String? = "",
    @SerializedName("start_date") var startDate: String? = null,
    @SerializedName("start_time") var startTime: String? = "",
    @SerializedName("status") var status: String? = "",
    @SerializedName("title") var title: String? = "",
    @SerializedName("trainer_id") var trainerId: Int = 0,
    @SerializedName("video") var video: String? = "",
    @SerializedName("is_verified") var isVerified: Int = 0,
    @SerializedName("verified_by") var verifiedBy: Int = 0,
    @SerializedName("is_rejected") var isRejected: Int = 0,
    @SerializedName("paid_money_id") var paidMoneyId: Int = 0,
    @SerializedName("webinar_video") var webinarVideo: String? = "",
    @SerializedName("confrenceid") var conferenceId: Int = 0,
    @SerializedName("topic") var topic: String? = "",
    @SerializedName("roomname") var roomName: String? = "",
    @SerializedName("room_pass") var room_pass: Int = 0,
    @SerializedName("videomeet_host_id") var videomeetHostId: Int = 0,
    var shouldShowChild: Boolean = false,
) :Serializable